language: cpp
addons:
  apt:
    sources:
      - george-edison55-precise-backports
    packages:
      - cmake-data
      - cmake
script:
  - sudo apt-get install libeigen3-dev python3.6
  - git submodule update --init --recursive
  - mkdir build
  - cd build
  - cmake ..
  - make
