platform: x64
configuration: Debug
branches:
  only:
  - master
clone_script:
- cmd: git clone -q --recursive --branch=%APPVEYOR_REPO_BRANCH% https://github.com/%APPVEYOR_REPO_NAME%.git %APPVEYOR_BUILD_FOLDER%
install:
  - ps: wget http://bitbucket.org/eigen/eigen/get/3.3.4.zip -outfile eigen3.zip
  - cmd: 7z x eigen3.zip -o"C:\projects" -y > nul

build_script:
 - mkdir build
 - cd build
 - cmake -DGMP_INCLUDE_DIR:STRING="gmp_lib" -DGMP_LIBRARY_C:STRING="gmp_lib/Debug/lib/libgmp-3" -DGMP_LIBRARY_CPP:STRING="gmp_lib/Debug/lib/libgmpxx-3" -D EIGEN3_INCLUDE_DIR=C:\projects\eigen-eigen-5a0156e40feb .. 
 - cmake --build . --config Debug 
