platform: x64
configuration: Debug
branches:
  only:
  - master

build_script:
 - mkdir build
 - cd build
 - cmake -DGMP_INCLUDE_DIR:STRING="gmp_lib/Debug/" -DGMP_LIBRARY_C:STRING="gmp_lib/Debug/lib/libgmp-3.lib" -DGMP_LIBRARY_CPP:STRING="gmp_lib/Debug/lib/libgmpxx-3.lib".. 
 - cmake --build . --config Debug 
